version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cache
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
